#################################################################################
##################################################################################
##    Copyright (C) 2019-present Prominic.NET, Inc.                             ##
##                                                                              ##
##    This program is free software: you can redistribute it and/or modify      ##
##    it under the terms of the Server Side Public License, version 1,          ##
##    as published by MongoDB, Inc.                                             ##
##                                                                              ##
##    This program is distributed in the hope that it will be useful,           ##
##    but WITHOUT ANY WARRANTY; without even the implied warranty of            ##
##    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             ##
##    Server Side Public License for more details.                              ##
##                                                                              ##
##    You should have received a copy of the Server Side Public License         ##
##    along with this program. If not, see:                                     ##
##                                                                              ##
##    http://www.mongodb.com/licensing/server-side-public-license               ##
##                                                                              ##
##    As a special exception, the copyright holders give permission to link the ##
##    code of portions of this program with the OpenSSL library under certain   ##
##    conditions as described in each individual source file and distribute     ##
##    linked combinations including the program with the OpenSSL library. You   ##
##    must comply with the Server Side Public License in all respects for       ##
##    all of the code used other than as permitted herein. If you modify file(s)##
##    with this exception, you may extend this exception to your version of the ##
##    file(s), but you are not obligated to do so. If you do not wish to do so, ##
##    delete this exception statement from your version. If you delete this     ##
##    exception statement from all source files in the program, then also delete##
##    it in the license file.                                                   ##
##################################################################################
##################################################################################
--- 
hosts: 
  - 
    autostart: true
    box: "peru/ubuntu-18.04-server-amd64"
    branch: 
    folders: 
      - 
        map: ./conf
        to: /vagrant
    gateway: "192.168.2.1"
    identifier: docova-new.int.dc-01.m4kr.net
    ip: "192.168.2.76"
    mac: 525400c9c010
    name: Docova-2-new
    netmask: "255.255.255.0"
    database_name: docova_db
    database_user: docova_user
    database_password: RandH38Uy
    mysql_root_password: mysql_root_password
    ldap_username: example@username.com
    ldap_password: RandH38Uy
    ldap_domain: MVCS
    ldap_adkey: SamAccountName
    ldap_groupkey: DisplayName
    mailer_user: "mailer@example.docova.net"
    mailer_password: RandH38Uy
    sender_address: "mailer@example.docova.net"
    client_id: 1234-1234-1234-1234
    client_secret: UyRandH38UyRandH38UyRan
    client_directory: 123-123-123-123
    google_api_key: RandH38UyRandH38UyRandH38Uy
    weather_api_key: RandH38UyRandH38UyRandH38UyRandH38Uy
    provider: 
      - 
        directive: memory
        value: "4096"
      - 
        directive: cpus
        value: "2"
    provision: 
      - ./scripts/aliases.sh
path: "."
