--- 
- 
  become: true
  file: 
    group: www-data
    mode: 493
    owner: www-data
    path: /var/html/www/
    state: directory
  name: "Create webroot"
- 
  name: "Check if Docova directory exists in /var/html/www/docova"
  register: check_path
  stat: path=/var/html/www/docova
- 
  copy: 
    dest: /tmp/docova.zip
    src: /vagrant/roles/www-data/templates/docova.zip
  name: "Copying Docova Bundle Zip"
- 
  become: true
  name: "Extract Docova"
  unarchive: 
    copy: false
    dest: /tmp
    group: www-data
    owner: www-data
    src: /tmp/docova.zip
  when: "not check_path.stat.exists"
- 
  become: true
  command: "mv /tmp/docova /var/html/www/docova"
  name: "Move Docova install files"
  notify: 
    - "restart nginx"
  when: "not check_path.stat.exists"
- 
  become: true
  file: 
    group: www-data
    mode: 493
    owner: www-data
    path: "{{ document_root }}"
    state: directory
  name: "Create document_root"
- 
  name: "Check if Docova directory exists in {{ document_root }}"
  register: check_path
  stat: "path={{ document_root }}"
- 
  become: true
  file: 
    group: www-data
    mode: 493
    owner: www-data
    path: 
      item: ~
    state: directory
  name: "Set Docova Document Permissions"
  with_items: 
    - /var/html/www/docova/src/Docova/DocovaBundle/Agents
    - /var/html/www/docova/src/Docova/DocovaBundle/Resources/public/css/custom
    - /var/html/www/docova/src/Docova/DocovaBundle/Resources/images
    - /var/html/www/docova/src/Docova/DocovaBundle/Resources/public/js/custom
    - /var/html/www/docova/src/Docova/DocovaBundle/Resources/views/DesignElements
    - /var/html/www/docova/var/logs
    - /var/html/www/docova/var/sessions
    - /var/html/www/docova/var/cache
    - /var/html/www/docova/web/upload
    - "{{ document_root }}"
- 
  lineinfile: 
    dest: /var/html/www/docova/app/config/parameters.yml
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  name: "Update Docova config file"
  notify: 
    - "restart nginx"
    - "restart php7.1-fpm"
  with_items: 
    - 
      line: "    database_driver: pdo_mysql"
      regexp: "database_driver:"
    - 
      line: "    database_port: 3306"
      regexp: "database_port:"
    - 
      line: "    database_name: {{database_name}}"
      regexp: "database_name:"
    - 
      line: "    database_user: {{database_user}}"
      regexp: "database_user:"
    - 
      line: "    database_password: {{database_password}}"
      regexp: "database_password:"
- 
  cron: 
    job: "sudo bash /var/html/www/docova/autoindex.sc"
    minute: "*/5"
    name: Autoindex
  name: "Setting Autoindex Cron Job"
- 
  cron: 
    job: "sudo bash /var/html/www/docova/dailylifecycle.sc"
    minute: "0"
    name: DailyLifeCycle
  name: "Setting DailyLifeCycle Cron Job"
- 
  become: true
  name: "Running setUpDOCOVA"
  shell: |-
      bash cd setUpDOCOVA.sc <<EOF
      y
      EOF
