--- 
- 
  apt: "upgrade=dist update_cache=yes"
  name: "Upgrade System"
- 
  apt_repository: 
    repo: "ppa:certbot/certbot"
  name: "Add certbot repository"
- 
  apt: 
    name: python-certbot-nginx
    state: present
  name: "Install Certbot's Nginx package"
- 
  name: "Check if certificate already exists."
  register: letsencrypt_cert
  stat: 
    path: "/etc/letsencrypt/live/{{ item.servername}}/cert.pem"
  with_items: "{{ apache_vhosts }}"
- 
  name: "Stop services to allow certbot to generate a cert."
  service: 
    name: "{{ item }}"
    state: stopped
  with_items: "{{ certbot_create_standalone_stop_services }}"
- 
  name: "Generate new"
  shell: "certbot certonly --standalone --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ item.item.servername}}"
  with_items: "{{ letsencrypt_cert.results }}"
- 
  name: "Start services after cert has been generated."
  service: 
    name: "{{ item }}"
    state: started
  with_items: "{{ certbot_create_standalone_stop_services }}"
