--- 
- 
  apt: "upgrade=dist update_cache=yes"
  name: "Upgrade System"
- 
  apt_repository: 
    repo: "ppa:certbot/certbot"
  name: "Add certbot repository"
- 
  apt: 
    name: python-certbot-nginx
    state: present
  name: "Install Certbot's Nginx package"
- 
  name: "Check if certificate already exists."
  register: letsencrypt_cert
  stat: 
    path: "/etc/letsencrypt/live/{{ item.servername}}/cert.pem"
  with_items: "{{ apache_vhosts }}"
- 
  name: "Stop services to allow certbot to generate a cert."
  service: 
    name: "{{ item }}"
    state: stopped
  with_items: "{{ certbot_create_standalone_stop_services }}"
- 
  name: "Generate new Certificate request"
  shell: "certbot certonly --standalone --noninteractive --agree-tos --email {{ certbot_admin_email }} -d {{ item.item.servername}}"
  with_items: "{{ letsencrypt_cert.results }}"
- 
  name: "Start services after cert has been generated."
  service: 
    name: "{{ item }}"
    state: started
  with_items: "{{ certbot_create_standalone_stop_services }}"
- 
  lineinfile: 
    dest: "/etc/nginx/sites-enabled/{{ id }}"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
  name: "Enabling SSL in Nginx"
  notify: 
    - "restart nginx"
    - "restart php7.1-fpm"
  with_items: 
    - 
      line: "    #ssl_certificate"
      regexp: "ssl_certificate  /etc/letsencrypt/live/{{ id }}/fullchain.pem;"
    - 
      line: "    #ssl_certificate_key"
      regexp: "ssl_certificate_key /etc/letsencrypt/live/{{ id }}/privkey.pem;"
    - 
      line: "    #ssl_protocols"
      regexp: "ssl_protocols TLSv1 TLSv1.1 TLSv1.2;"
    - 
      line: "    #ssl_ciphers"
      regexp: "ssl_ciphers HIGH:!aNULL:!MD5;"
