<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppDocCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppDocCommentsRepository extends EntityRepository
{


	/**
	 * Get all application files data array/xml for view
	 *
	 * @param string $app_id
	 * @param string $format
	 * @return array
	 */
	public function getCommentFieldValues($unid)
	{
		$query = $this->createQueryBuilder('V')
			->select(array( 'D.id',  'CB.userNameDnAbbreviated', 'V.threadIndex','V.commentIndex','V.avatar', 'V.dateCreated', 'V.comment' ))
			->join('V.createdBy', 'CB')
			->join('V.document', 'D')
			->where('V.id = :unid')
			->setParameter('unid', $unid)
			->getQuery();
		
		$result = $query->getArrayResult();
		
		if (!empty($result[0])) 
		{
			return $result[0];
		}
		
		return array();
	}


	/**
	 * Get all application files data array/xml for view
	 *
	 * @param string $app_id
	 * @param string $format
	 * @return array
	 */
	public function getDocComments($unid)
	{
		$query = $this->createQueryBuilder('V')
			->select(array( 'V.id' ,  'CB.userNameDnAbbreviated', 'V.threadIndex','V.commentIndex','V.avatar', 'V.dateCreated', 'V.comment' ))
			->join('V.createdBy', 'CB')
			->join('V.document', 'D')
			->where('V.document = :unid')
			->addOrderBy('V.threadIndex', 'DESC')
			->addOrderBy('V.commentIndex', 'ASC')
			->setParameter('unid', $unid)
			->getQuery();
		
		$result = $query->getArrayResult();
		


		if (!empty($result)) 
		{
			return $result;
		}
		
		return array();
	}
	
}
