<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppFilesRepository extends EntityRepository
{
	/**
	 * Get all application files data array/xml for view
	 *
	 * @param string $app_id
	 * @param string $format
	 * @return array
	 */
	public function getViewData($app_id, $format = 'array')
	{
		$output = array('@timestamp' => time(), '@toplevelentries' => '0');
		$query = $this->createQueryBuilder('F')
			->join('F.application', 'A')
			->where('F.application = :app')
			->andWhere('A.Trash = false')
			->andWhere('A.isApp = true')
			->addOrderBy('F.fileName', 'ASC')
			->setParameter('app', $app_id)
			->getQuery();
	
		$result = $query->getResult();
	
		if (!empty($result))
		{
			if ($format === 'array')
			{
				$output['@toplevelentries'] = count($result);
				$output['viewentry'] = array();
				foreach ($result as $file) {
					$output['viewentry'][] = array(
						'@unid' => $file->getId(),
						'entrydata' => array(
							array('text' => array($file->getFileName())),
							array('datetime' => array('@dst'=>true, 0 => $file->getDateModified()->format('Ymd his'))),
							array('text' => array($file->getModifiedBy()->getUserNameDnAbbreviated())),
							array('text' => array($file->getPDU() ? 'Yes' : 'No'))
						)
					);
				}
			}
			else {
				$xml = '<viewentries timestamp="'.time().'" toplevelentries="'.count($result).'">';
				foreach ($result as $file) {
					$xml .= "<viewentry unid='{$file->getId()}'>";
					$xml .= "<entrydata columnnumber='0'><text>{$file->getFileName()}</text></entrydata>";
					$xml .= "<entrydata columnnumber='1'><datetime dst='true'>{$file->getDateModified()->format('Ymd his')}</datetime></entrydata>";
					$xml .= "<entrydata columnnumber='2'><text>{$file->getModifiedBy()->getUserNameDnAbbreviated()}</text></entrydata>";
					$xml .= '<entrydata columnnumber="3"><text>'.($file->getPDU() ? 'Yes' : 'No').'</text></entrydata>';
					$xml .= '</viewentry>';
				}
				$xml .= '</viewentries>';
				$output = $xml;
			}
			$result = $file = null;
		}
		elseif ($format !== 'array') {
			$output = '<viewentries timestamp="'.time().'" toplevelentries="0"></viewentries>';
		}
		return $output;
	}
}
