<?php

namespace Docova\DocovaBundle\Entity;

/**
 * AppGroupsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppGroupsContentRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get list of apps/libraries/library groups in the app-group
	 * 
	 * @param string $app_group
	 * @return array
	 */
	public function getAppGroupList($app_group)
	{
		$query = $this->createQueryBuilder('GC')
			->select(['GC.id', 'A.id AS AppId' ,'LG.id AS LibGroupId', 'A.Library_Title', 'A.appIcon', 'A.appIconColor', 'A.Description', 'A.Is_Template', 'A.isApp', 'LG.groupTitle', 'LG.groupIcon', 'LG.groupIconColor', 'LG.groupDescription', 'IDENTITY(LG.createdBy) AS createdBy'])
			->leftJoin('GC.application', 'A')
			->leftJoin('GC.libraryGroup', 'LG')
			->where('GC.appGroup = :appgroup')
			->setParameter('appgroup', $app_group)
			->orderBy('A.Library_Title', 'ASC')
			->orderBy('LG.groupTitle', 'ASC')
			->getQuery();
		
		$result = $query->getArrayResult();
		if (!empty($result)) {
			return $result;
		}
		return [];
	}
}
