<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppLayoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppLayoutRepository extends EntityRepository
{
	/**
	 * Get all application forms data array/xml for view
	 *
	 * @param string $app_id
	 * @param string $format
	 * @return array
	 */
	public function getViewData($app_id, $format = 'array')
	{
		$output = array('@timestamp' => time(), '@toplevelentries' => '0');
		$query = $this->createQueryBuilder('L')
			->join('L.application', 'A')
			->where('L.application = :app')
			->andWhere('A.Trash = false')
			->andWhere('A.isApp = true')
			->addOrderBy('L.layoutId', 'ASC')
			->addOrderBy('L.layoutAlias', 'ASC')
			->setParameter('app', $app_id)
			->getQuery();
	
		$result = $query->getResult();
	
		if (!empty($result))
		{
			if ($format === 'array')
			{
				$output['@toplevelentries'] = count($result);
				$output['viewentry'] = array();
				foreach ($result as $layout) {
					$output['viewentry'][] = array(
						'@unid' => $layout->getId(),
						'entrydata' => array(
							array('text' => array($layout->getLayoutId())),
							array('html' => array($layout->getLayoutDefault() ? '<i  class="far fa-thumbs-up"></i>' : '')),
							array('datetime' => array('@dst'=>true, 0 => $layout->getDateModified()->format('Ymd his'))),
							array('text' => array($layout->getModifiedBy()->getUserNameDnAbbreviated())),
							array('text' => array($layout->getProhibitDesignUpdate() ? 'Yes' : 'No'))
						)
					);
				}
			}
			else {
				$xml = '<viewentries timestamp="'.time().'" toplevelentries="'.count($result).'">';
				foreach ($result as $layout) {
					$xml .= "<viewentry unid='{$layout->getId()}'>";
					$xml .= "<entrydata columnnumber='0'><text><![CDATA[{$layout->getLayoutId()}]]></text></entrydata>";
					$xml .= "<entrydata columnnumber='1'><html>".($layout->getLayoutDefault() ? '<i  class="far fa-thumbs-up"></i>' : '')."</html></entrydata>";
					$xml .= "<entrydata columnnumber='2'><datetime dst='true'>{$layout->getDateModified()->format('Ymd his')}</datetime></entrydata>";
					$xml .= "<entrydata columnnumber='3'><text><![CDATA[{$layout->getModifiedBy()->getUserNameDnAbbreviated()}]]></text></entrydata>";
					$xml .= '<entrydata columnnumber="4"><text>'.($layout->getProhibitDesignUpdate() ? 'Yes' : 'No').'</text></entrydata>';
					$xml .= '<entrydata columnnumber="5"><text><![CDATA['.$layout->getLayoutId().'|'.$layout->getLayoutAlias().']]></text></entrydata>';
					$xml .= '</viewentry>';
				}
				$xml .= '</viewentries>';
				$output = $xml;
			}
			$result = $layout = null;
		}
		elseif ($format !== 'array') {
			$output = '<viewentries timestamp="'.time().'" toplevelentries="0"></viewentries>';
		}
		return $output;
	}
	
	/**
	 * Find a layout by name or alias
	 * 
	 * @param string $layout
	 * @param string $appid
	 * @return AppLayout
	 */
	public function findLayout($layout, $appid)
	{
		$query = $this->createQueryBuilder('L')
			->join('L.application', 'A')
			->where('L.application = :app')
			->andWhere('L.layoutId = :layout OR L.layoutAlias = :layout')
			->andWhere('A.Trash = false')
			->andWhere('A.isApp = true')
			->setParameter('layout', $layout)
			->setParameter('app', $appid)
			->setMaxResults(1)
			->getQuery();
		
		$result = $query->getSingleResult();
		return $result;
	}
	
	/**
	 * Reset default layout in app
	 * 
	 * @param string $appid
	 */
	public function resetDefaultLayout($appid)
	{
		$query = $this->createQueryBuilder('L')
			->update()
			->set('L.layoutDefault', ':default')
			->where('L.layoutDefault = true')
			->andWhere('L.application = :app')
			->setParameter('default', false)
			->setParameter('app', $appid)
			->getQuery();
		
		$query->execute();
	}
}
