<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppOutlinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppOutlinesRepository extends EntityRepository
{
	/**
	 * Get all application outlines data array/xml for view
	 *
	 * @param string $app_id
	 * @param string $format
	 * @return array
	 */
	public function getViewData($app_id, $format = 'array')
	{
		$output = array('@timestamp' => time(), '@toplevelentries' => '0');
		$query = $this->createQueryBuilder('O')
			->join('O.application', 'A')
			->where('O.application = :app')
			->andWhere('A.Trash = false')
			->andWhere('A.isApp = true')
			->addOrderBy('O.outlineName', 'ASC')
			->addOrderBy('O.outlineAlias', 'ASC')
			->setParameter('app', $app_id)
			->getQuery();
	
		$result = $query->getResult();
	
		if (!empty($result))
		{
			if ($format === 'array')
			{
				$output['@toplevelentries'] = count($result);
				$output['viewentry'] = array();
				foreach ($result as $outline) {
					$output['viewentry'][] = array(
						'@unid' => $outline->getId(),
						'entrydata' => array(
							array('text' => array($outline->getOutlineName())),
							array('text' => array($outline->getOutlineAlias())),
							array('datetime' => array('@dst'=>true, 0 => $outline->getDateModified()->format('Ymd his'))),
							array('text' => array($outline->getModifiedBy()->getUserNameDnAbbreviated())),
							array('text' => array($outline->getPDU() ? 'Yes' : 'No'))
						)
					);
				}
			}
			else {
				$xml = '<viewentries timestamp="'.time().'" toplevelentries="'.count($result).'">';
				foreach ($result as $outline) {
					$xml .= "<viewentry unid='{$outline->getId()}'>";
					$xml .= "<entrydata columnnumber='0'><text><![CDATA[{$outline->getOutlineName()}]]></text></entrydata>";
					$xml .= "<entrydata columnnumber='1'><text><![CDATA[{$outline->getOutlineAlias()}]]></text></entrydata>";
					$xml .= "<entrydata columnnumber='2'><datetime dst='true'>{$outline->getDateModified()->format('Ymd his')}</datetime></entrydata>";
					$xml .= "<entrydata columnnumber='3'><text>{$outline->getModifiedBy()->getUserNameDnAbbreviated()}</text></entrydata>";
					$xml .= '<entrydata columnnumber="4"><text>'.($outline->getPDU() ? 'Yes' : 'No').'</text></entrydata>';
					$xml .= '<entrydata columnnumber="5"><text><![CDATA['.$outline->getOutlineName().'|'.$outline->getOutlineAlias().']]></text></entrydata>';
					$xml .= '</viewentry>';
				}
				$xml .= '</viewentries>';
				$output = $xml;
			}
			$result = $outline = null;
		}
		elseif ($format !== 'array') {
			$output = '<viewentries timestamp="'.time().'" toplevelentries="0"></viewentries>';
		}
		return $output;
	}
	/**
	 * Find view by view name or alias
	 * 
	 * @param string $name
	 * @param string $appid
	 * @return \Docova\DocovaBundle\Entity\AppViews|null
	 */
	public function findByNameAlias($name, $appid)
	{
		$query = $this->createQueryBuilder('V')
			->where('V.application = :app')
			->andWhere('V.outlineName = :vname OR V.outlineAlias = :vname')
			->setParameter('app', $appid)
			->setParameter('vname', $name)
			->getQuery();
		
		try {
			$result = $query->getSingleResult();
			return $result;
		}
		catch (\Exception $e) {
//			var_dump($e->getMessage());
			return null;
		}
	}
}
