<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppPagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppPagesRepository extends EntityRepository
{
	/**
	 * Get all application pages data array/xml for view
	 *
	 * @param string $app_id
	 * @param string $format
	 * @return array
	 */
	public function getViewData($app_id, $format = 'array')
	{
		$output = array('@timestamp' => time(), '@toplevelentries' => '0');
		$query = $this->createQueryBuilder('P')
			->join('P.application', 'A')
			->where('P.application = :app')
			->andWhere('A.Trash = false')
			->andWhere('A.isApp = true')
			->addOrderBy('P.pageName', 'ASC')
			->addOrderBy('P.pageAlias', 'ASC')
			->setParameter('app', $app_id)
			->getQuery();
	
		$result = $query->getResult();
	
		if (!empty($result))
		{
			if ($format === 'array')
			{
				$output['@toplevelentries'] = count($result);
				$output['viewentry'] = array();
				foreach ($result as $page) {
					$output['viewentry'][] = array(
						'@unid' => $page->getId(),
						'entrydata' => array(
							array('text' => array($page->getPageName())),
							array('text' => array($page->getPageAlias())),
							array('datetime' => array('@dst'=>true, 0 => $page->getDateModified()->format('Ymd his'))),
							array('text' => array($page->getModifiedBy()->getUserNameDnAbbreviated())),
							array('text' => array($page->getPDU() ? 'Yes' : 'No'))
						)
					);
				}
			}
			else {
				$xml = '<viewentries timestamp="'.time().'" toplevelentries="'.count($result).'">';
				foreach ($result as $page) {
					$xml .= "<viewentry unid='{$page->getId()}'>";
					$xml .= "<entrydata columnnumber='0'><text><![CDATA[{$page->getPageName()}]]></text></entrydata>";
					$xml .= "<entrydata columnnumber='1'><text><![CDATA[{$page->getPageAlias()}]]></text></entrydata>";
					$xml .= "<entrydata columnnumber='2'><datetime dst='true'>{$page->getDateModified()->format('Ymd his')}</datetime></entrydata>";
					$xml .= "<entrydata columnnumber='3'><text>{$page->getModifiedBy()->getUserNameDnAbbreviated()}</text></entrydata>";
					$xml .= '<entrydata columnnumber="4"><text>'.($page->getPDU() ? 'Yes' : 'No').'</text></entrydata>';
					$xml .= '<entrydata columnnumber="5"><text><![CDATA['.$page->getPageName().'|'.$page->getPageAlias().']]></text></entrydata>';
					$xml .= '</viewentry>';
				}
				$xml .= '</viewentries>';
				$output = $xml;
			}
			$result = $page = null;
		}
		elseif ($format !== 'array') {
			$output = '<viewentries timestamp="'.time().'" toplevelentries="0"></viewentries>';
		}
		return $output;
	}
	
	/**
	 * Find page by name or alias
	 * 
	 * @param string $page_name
	 * @param string $app_id
	 * @return \Docova\DocovaBundle\Entity\AppPages
	 */
	public function findPage($page_name, $app_id)
	{
		$query = $this->createQueryBuilder('P')
			->join('P.application', 'A')
			->where('P.application = :app')
			->andWhere('A.Trash = false')
			->andWhere('A.isApp = true')
			->andWhere('P.pageName = :pagename OR P.pageAlias = :pagename')
			->setParameter('app', $app_id)
			->setParameter('pagename', $page_name)
			->getQuery();
	
		$result = $query->getSingleResult();
		return $result;
	}
}
