<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocTypeFieldsPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocTypeFieldsPropertyRepository extends EntityRepository
{
	public function getDocTypeAllProperties($DocType, $Field)
	{
		$query = $this->createQueryBuilder('DTP')
			->where('DTP.DocumentType = :DocType AND DTP.Field = :Field')
			->setParameters(array('DocType'=>$DocType, 'Field'=>$Field))
			->getQuery();
		
		$result = $query->getOneOrNullResult();

		return $result;
	}
}