<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentCommentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentCommentsRepository extends EntityRepository
{
	/**
	 * Get all comments need to be presented in Log Comments Section
	 * 
	 * @param string $document
	 * @return mixed
	 */
	public function getDocumentLogComments($document)
	{
		$query = $this->createQueryBuilder('C')
			->where('C.Comment_Type > 0')
			->andWhere('C.Document = :doc')
			->setParameter('doc', $document)
			->getQuery();
		
		$result = $query->getResult();
		return $result;
	}

	/**
	 * Get all comments of a document
	 * 
	 * @param string $document
	 * @return multitype:
	 */
	public function getDocumentComments($document)
	{
		$query = $this->createQueryBuilder('C')
			->join('C.Created_By', 'CB')
			->addSelect('CB')
			->where('C.Document = :doc')
			->setParameter('doc', $document)
			->addOrderBy('C.Date_Created', 'ASC')
			->getQuery();
		
		$result = $query->getResult();
		return $result;
	}
}