<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentsLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentsLogRepository extends EntityRepository
{
	/**
	 * Get all workflow comments of a document
	 *
	 * @param string $document
	 * @return multitype:
	 */
	public function getDocWorkflowComments($document)
	{
		$query = $this->createQueryBuilder('L')
			->join('L.Log_Author', 'LA')
			->addSelect('LA')
			->where('L.Document = :doc')
			->andWhere('L.Log_Action = 5')
			->setParameter('doc', $document);
		$query->andWhere($query->expr()->like('L.Log_Details', $query->expr()->literal('%workflow step. Comments:%')))
			->addOrderBy('L.Log_Date', 'ASC');

		$result = $query->getQuery()->getResult();
		return $result;
	}
}