<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FacetMapsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacetMapsRepository extends EntityRepository
{

	/**
	 * Select all valid Facet Maps, either system default facet maps or none system ones
	 * 
	 * @param integer $library_id
	 * @return array|mixed
	 */
	public function findAllValidFacetMaps($library_id)
	{
		$query = $this->createQueryBuilder('FM')
				->where('FM.Library IS NULL OR FM.Library = :lib_id')
				->setParameter('lib_id', $library_id)
				->getQuery();
		
		$result = $query->getResult();
		if (!empty($result))
		{
			return $result;
		}
		
		return array();
	}

	/**
	 * Get the first system default facet map
	 * 
	 * @return object|null
	 */
	public function getSystemDefaultFacetMap()
	{
		$query = $this->createQueryBuilder('FM')
				->where("FM.Library IS NULL AND FM.Default_Facet = 'facetmap'")
				->orderBy('FM.id', 'ASC')
				->getQuery();
		
		$result = $query->getOneOrNullResult();
		
		return $result;
	}
}