<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileTemplatesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileTemplatesRepository extends EntityRepository
{
	public function getDataXML($criteria = array(), $sortBy = array(), $return_obj = false)
	{
		if (empty($criteria) && empty($sortBy)) {
			$templates = $this->findAll();
		}
		else {
			$orderBy = array();
			if (!empty($sortBy)) 
			{
				foreach ($sortBy as $key => $value) {
					if ($this->_class->hasField($key)) {
						$orderBy[$key] = strtoupper($value) == 'DESC' ? 'DESC' : 'ASC';
					}
					else {
						if ($key == 'type' && !empty($value)) {
							$orderBy['Template_Type'] = strtoupper($value) == 'DESC' ? 'DESC' : 'ASC';
						}
						elseif ($key == 'templatename' && !empty($value)) {
							$orderBy['Template_Name'] = strtoupper($value) == 'DESC' ? 'DESC' : 'ASC';
						}
					}
				}
			}
			$templates = $this->findBy($criteria, $orderBy);
		}
		
		$data_xml = ($return_obj === false) ? array() : new \DOMDocument('1.0', 'UTF-8');
		foreach ($templates as $doc)
		{
			if ($return_obj === false)
			{
				$data_xml[] = array(
					'dockey' => $doc->getId(),
					'type' => $doc->getTemplateType(),
					'templatename' => $doc->getTemplateName()
				);
/*
				$data_xml .= '<document>';
				$data_xml .= '<dockey>'.$doc->getId().'</dockey>';
				$data_xml .= '<docid>'.$doc->getId().'</docid>';
				$data_xml .= '<rectype>doc</rectype>';
				$data_xml .= '<type><![CDATA['.$doc->getTemplateType().']]></type>';
				$data_xml .= '<templatename><![CDATA[]]>'.$doc->getTemplateName().'</templatename>';
				$data_xml .= '<statno />';
				$data_xml .= '<wfstarted />';
				$data_xml .= '<delflag />';
				$data_xml .= '</document>';
*/
			}
			else {
				$root = $data_xml->appendChild($data_xml->createElement('document'));
				$root->appendChild($data_xml->createElement('dockey', $doc->getId()));
				$root->appendChild($data_xml->createElement('docid', $doc->getId()));
				$root->appendChild($data_xml->createElement('rectype', 'doc'));
				$cdata = $data_xml->createCDATASection($doc->getTemplateType());
				$newnode = $data_xml->createElement('type');
				$newnode->appendChild($cdata);
				$root->appendChild($newnode);
				$cdata = $data_xml->createCDATASection($doc->getTemplateName);
				$newnode = $data_xml->createElement('templatename');
				$newnode->appendChild($cdata);
				$root->appendChild($newnode);
			}
		}
		
		return $data_xml;
	}
	
	/*
	 * Deletes documents from web admin view
	* @param: xml data with id to delete
	* @return: xml Data response
	*/
	public function deleteSelectedDocuments($post_xml){
	
		$deleted=0;
	
		foreach ($post_xml->getElementsByTagName('Unid') as $doc_id)
		{
			$document = $this->find($doc_id->nodeValue);
			if (!empty($document))
			{
				$this->_em->remove($document);
				$deleted++;
				$this->_em->flush(); // commit each delete
			}
	
		}
		// setup return xml
		$response_xml = new \DOMDocument("1.0", "UTF-8");
		$root = $response_xml->appendChild($response_xml->createElement('Results'));
		if ($deleted !== 0)
		{
			$child = $response_xml->createElement('Result', 'OK');
			$attrib = $response_xml->createAttribute('ID');
			$attrib->value = 'Status';
			$child->appendChild($attrib);
			$root->appendChild($child);
	
			$child = $response_xml->createElement('Result', $deleted);
			$attrib = $response_xml->createAttribute('ID');
			$attrib->value = 'Ret1';
			$child->appendChild($attrib);
			$root->appendChild($child);
		}
		else {
			$child = $response_xml->createElement('Result', 'FAILED');
			$attrib = $response_xml->createAttribute('ID');
			$attrib->value = 'Status';
			$child->appendChild($attrib);
			$root->appendChild($child);
	
			$child = $response_xml->createElement('Result', 'Could not delete one or more of the selected documents.');
			$attrib = $response_xml->createAttribute('ID');
			$attrib->value = 'ErrMsg';
			$child->appendChild($attrib);
			$root->appendChild($child);
		}
		return $response_xml->saveXML();
	}
	
	/**
	 * Get templates list by IDs
	 * 
	 * @param array $template_ids
	 * @return object[]
	 */
	public function getTemplatesByIds($template_ids)
	{
		if (empty($template_ids))
			return array();
		
		$query = $this->createQueryBuilder('T');
		if (count($template_ids) == 1)
		{
			$query->where('T.id = :template')
				->setParameter('template', $template_ids[0]);
		}
		else {
			$query->expr()->in('T.id', $template_ids);
		}
		
		$result = $query->getQuery()->getResult();
		return $result;
	}

	/**
	 * Get template by name
	 * 
	 * @param string templatename
	 * @return object[]
	 */
	public function getTemplateByName($template_name)
	{
		if (empty($template_name))
			return null;
		
		$query = $this->createQueryBuilder('T');
		$query->where('T.Template_Name = :template')
				->setParameter('template', $template_name);
		
		
		$result = $query->getQuery()->getResult();
		return (!empty($result) ? $result[0] : null);
	}
}