<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalSettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalSettingsRepository extends EntityRepository 
{
	/**
	 * {@inheritDoc}
	 * @see \Doctrine\ORM\EntityRepository::findAll()
	 */
	public function findAll()
	{
		$result = $this->createQueryBuilder('G')
			->getQuery()
			->useResultCache(true)
			->setResultCacheId('gsettings_cache_id')
			->getResult();
		
		return $result;
	}
}