<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MigratedAppACE
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MigratedAppACERepository extends EntityRepository
{
}