<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RelatedDocumentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelatedDocumentsRepository extends EntityRepository 
{
	/**
	 * Find all linked documents either as parent or child
	 * 
	 * @param integer $document
	 * @return array
	 */
	public function findLinkedDocuments($document)
	{
		$query = $this->createQueryBuilder('RD')
			->where('RD.Parent_Doc = :document')
			->orWhere('RD.Related_Doc = :document')
			->setParameter('document', $document)
			->getQuery();
		
		return $query->getResult();
	}
	
	/**
	 * Check if document is a response document
	 * 
	 * @param string $document
	 * @return boolean
	 */
	public function isResponse($document)
	{
		$query = $this->createQueryBuilder('R')
			->select('COUNT(R.id)')
			->where('R.Related_Doc = :document')
			->setParameter('document', $document)
			->getQuery();
		
		$result = $query->getSingleScalarResult();
		if (!empty($result))
			return true;
		
		return false;
	}
}