<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SavedSearchesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SavedSearchesRepository extends EntityRepository
{
	/**
	 * Get the user saved searches in library(ies)
	 * 
	 * @param string $user
	 * @param array $libraries
	 * @return array
	 */
	public function getUserSavedSearchesInLibraries($user, $libraries = array())
	{
		$query = $this->createQueryBuilder('SS')
			->where('SS.userSaved = :user')
			->setParameter('user', $user)
			->orderBy('SS.searchName', 'ASC');
		
		if (!empty($libraries)) 
		{
			$query->join('SS.libraries', 'L');
			if (count($libraries) == 1) 
			{
				$query->andWhere('L.id = :library')
					->setParameter('library', $libraries[0]);
			}
			else {
				$query->andWhere($query->expr()->in('L.id', $libraries));
			}
		}
		else {
			$query->andWhere('SS.globalSearch = true');
		}
		
		$result = $query->getQuery()->getResult();
		
		return $result;
	}
}
