<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubformsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubformsRepository extends EntityRepository 
{
	/**
	 * Get all application forms data array/xml for view
	 *
	 * @param string $app_id
	 * @param string $format
	 * @return array
	 */
	public function getViewData($app_id, $format = 'array')
	{
		$output = array('@timestamp' => time(), '@toplevelentries' => '0');
		$query = $this->createQueryBuilder('S')
			->join('S.application', 'A')
			->where('S.application = :app')
			->andWhere('S.Is_Custom = true')
			->andWhere('A.Trash = false')
			->andWhere('A.isApp = true')
			->addOrderBy('S.Form_Name', 'ASC')
			->setParameter('app', $app_id)
			->getQuery();
	
		$result = $query->getResult();
	
		if (!empty($result))
		{
			if ($format === 'array')
			{
				$output['@toplevelentries'] = count($result);
				$output['viewentry'] = array();
				foreach ($result as $form) {
					$output['viewentry'][] = array(
						'@unid' => $form->getId(),
						'entrydata' => array(
							array('text' => array($form->getFormFileName())),
							array('text' => array($form->getFormName())),
							array('datetime' => array('@dst'=>true, 0 => $form->getDateModified()->format('Ymd his'))),
							array('text' => array($form->getModifiedBy()->getUserNameDnAbbreviated())),
							array('text' => array($form->getPDU() ? 'Yes' : 'No'))
						)
					);
				}
			}
			else {
				$xml = '<viewentries timestamp="'.time().'" toplevelentries="'.count($result).'">';
				foreach ($result as $form) {
					$xml .= "<viewentry unid='{$form->getId()}'>";
					$xml .= "<entrydata columnnumber='0'><text>{$form->getFormFileName()}</text></entrydata>";
					$xml .= "<entrydata columnnumber='1'><text>{$form->getFormName()}</text></entrydata>";
					$xml .= "<entrydata columnnumber='2'><datetime dst='true'>{$form->getDateModified()->format('Ymd his')}</datetime></entrydata>";
					$xml .= "<entrydata columnnumber='3'><text>{$form->getModifiedBy()->getUserNameDnAbbreviated()}</text></entrydata>";
					$xml .= '<entrydata columnnumber="4"><text>'.($form->getPDU() ? 'Yes' : 'No').'</text></entrydata>';
					$xml .= '</viewentry>';
				}
				$xml .= '</viewentries>';
				$output = $xml;
			}
			$result = $form = null;
		}
		elseif ($format !== 'array') {
			$output = '<viewentries timestamp="'.time().'" toplevelentries="0"></viewentries>';
		}
		return $output;
	}

	/**
	 * Find subofmr by subform name or alias
	 * 
	 * @param string $name
	 * @param string $appid
	 * @return \Docova\DocovaBundle\Entity\Subforms|null
	 */
	public function findSubformByNameAlias($name, $appid)
	{
		$query = $this->createQueryBuilder('V')
			->where('V.application = :app')
			->andWhere('V.Form_Name = :vname OR V.Form_File_Name = :vname')
			->setParameter('app', $appid)
			->setParameter('vname', $name)
			->getQuery();
		
		try {
			$result = $query->getSingleResult();
			return $result;
		}
		catch (\Exception $e) {
//			var_dump($e->getMessage());
			return null;
		}
	}
}