<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TrashedLogsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrashedLogsRepository extends EntityRepository 
{
	/**
	 * Get all expired logs base on the library DocLog_Retention field
	 * 
	 * @return mixed
	 */
	public function getExpiredLogs()
	{
		$query = $this->createQueryBuilder('TL')
			->join('TL.parentLibrary', 'L')
			->where('L.Trash = false')
			->andWhere("DATE_ADD(TL.dateCreated, L.DocLog_Retention, 'DAY') <= CURRENT_TIMESTAMP()")
			->getQuery();
		
		return $query->getResult();
	}
}