<?php

namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRecentAppsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRecentAppsRepository extends EntityRepository
{
	/**
	 * Get latest 15 opened apps by the user
	 * 
	 * @param string $user
	 * @param integer $max
	 * @return Libraries[]
	 */
	public function getLatestOpenedApps($user, $max)
	{
		$apps = [];
		$query = $this->createQueryBuilder('LA')
			->leftJoin('LA.app', 'A')
			->leftJoin('LA.libgroup', 'LG')
			->addSelect('A')
			->addSelect('LG')
			->where('LA.user = :userid')
			->setParameter('userid', $user)
			->addOrderBy('LA.lastOpenDate', 'DESC');
			if(!empty($max)){
			    $query->setMaxResults($max);
			}
		
		$result = $query->getQuery()->getResult();
		if (!empty($result))
		{
			foreach ($result as $app)
			{
				if ($app->getApp()) {
					$apps[] = $app->getApp();
				}
				elseif ($app->getLibgroup()) {
					$apps[] = $app->getLibgroup();
				}
			}
		}
		
		return $apps;
	}
}
