<?php

namespace Docova\DocovaBundle\Entity;

/**
 * UserAppGroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAppGroupsRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Get user app-groups list
	 * 
	 * @param string $user
	 * @return array
	 */
	public function getUserAppGroups($user)
	{
		$query = $this->createQueryBuilder('AG')
			->where('AG.createdBy = :userid')
			->setParameter('userid', $user)
			->addOrderBy('AG.groupName', 'ASC')
			->getQuery();
		
		$result = $query->getArrayResult();
		if (!empty($result)) {
			return $result;
		}
		return [];
	}
}
