<?php
namespace Docova\DocovaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetsRepository
 * 
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetsRepository extends EntityRepository
{
	public function getViewData($is_custom = false, $format = 'array')
	{
		$output = ['@timestamp' => time(), '@toplevelentries' => '0'];
		$query = $this->createQueryBuilder('W')
			->where('W.isCustom = :custom')
			->setParameter('custom', $is_custom)
			->getQuery();
		
		$result = $query->getResult();
		
		if (!empty($result))
		{
			if ($format === 'array')
			{
				$output['@toplevelentries'] = count($result);
				$output['viewentry'] = [];
				foreach ($result as $widget) {
					$output['viewentry'][] = [
						'@unid' => $widget->getId(),
						'entrydata' => [
							['text' => [$widget->getWidgetName()]],
							['text' => [$widget->getDescription()]],
							['html' => [$widget->getInactive() ? '<i  class="fa fa-toggle-off fa-2x" style="color:#FA8072"></i>' : '<i  class="fa fa-toggle-on fa-2x" style="color:#32CD32"></i>']],
							['datetime' => ['@dst' => true, 0 => ($widget->getDateModified() ? $widget->getDateModified()->format('Ymd his') : '')]],
							['text' => [$widget->getDateModified() ? $widget->getModifiedBy()->getUserNameDnAbbreviated() : '']]
						]
					];
				}
			}
			else {
				$xml = '<viewentries timestamp="'.time().'" toplevelentries="'.count($result).'">';
				foreach ($result as $widget) {
					$xml .= "<viewentry unid='{$widget->getId()}'>";
					$xml .= "<entrydata columnnumber='0'><text><![CDATA[{$widget->getWidgetName()}]]></text></entrydata>";
					$xml .= "<entrydata columnnumber='1'><text><![CDATA[{$widget->getDescription()}]]></text></entrydata>";
					$xml .= '<entrydata columnnumber="2"><html>'.($widget->getInactive() ? '<i  class="fa fa-toggle-off fa-2x" style="color:#FA8072"></i>' : '<i  class="fa fa-toggle-on fa-2x" style="color:#32CD32"></i>').'</html></entrydata>';
					$xml .= "<entrydata columnnumber='3'><datetime dst='true'>{$widget->getDateModified()->format('Ymd his')}</datetime></entrydata>";
					$xml .= "<entrydata columnnumber='4'><text>{$widget->getModifiedBy()->getUserNameDnAbbreviated()}</text></entrydata>";
					$xml .= '</viewentry>';
				}
				$xml .= '</viewentries>';
				$output = $xml;
			}
			$result = $widget = null;
		}
		elseif ($format !== 'array') {
			$output = '<viewentries timestamp="'.time().'" toplevelentries="0">';
		}
		
		return $output;
	}
}